### ISSUE TITLE
Remove date automatically appearing on posts

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#23]

**Comment by windupmicheal** [comment]
Please indicate steps to repro and include a screenshot of where exactly you're talking about (these dates exist in multiple places - on posts, in the post listings pages, etc.). I think we should keep the date on some posts like the reports, since they are date-sensitive and not evergreen content..

Also wondering why we want to remove dates?

**Comment by philtackletrading** [comment]
I'll have pics for you Monday EOB. Tim's wanting dates removed particularly from evergreen content specifically so it can be utilized as drip content, but for the automatic dating, that would remove it from everything else, too.

**Comment by philtackletrading** [comment]
![dateremoval](https://cloud.githubusercontent.com/assets/20495058/18064431/a0a86e92-6dec-11e6-8aa7-c9ef270c5c37.jpg)Sample of where date should be removed from posts.

**Comment by windupmicheal** [comment]
Assigning to Leo and setting priority to medium.

**Comment by highwayjourney** [comment]
removed date. Please check if this is solved as you wanted.

**Comment by windupmicheal** [comment]
Fix verified on staging site. Closing bug.
