### ISSUE TITLE
Is Theta Fade forum still up for paid members, and when should it be taken down?

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#26]

**Comment by windupmicheal** [comment]
@highwayjourney - the "Theta Nation" forum needs to be removed from BBPress ASAP. You may want to work with @prakharbhatia as "Theta Nation" forum is for "Theta Fade" member access on Ontraport, so there may be some custom coding on the back end which limits access to this forum which may complicate removal. Let me know if you need assistance with this.

**Comment by highwayjourney** [comment]
These are all taken down. The original URLs now all redirect to default "not permitted" page.

**Comment by windupmicheal** [comment]
@highwayjourney To clarify: There should be no mention whatsoever of Theta Fade anywhere on the front-end of the website. The Theta Fade forum can be removed from the back end of the site along with other Theta Fade Wordpress Pages. However, the Theta Fade Sensei course should remain accessible via a private, unpublished URL for current subscribers. Please give Phil and Noah this URL. 

Also, http://tackletrade.staging.wpengine.com/theta-fade appears to still be functional. Please remove.

@NoahTackleTrading and @philtackletrading I'm removing ~all~ mentions of Theta Fade from the front end.. We'll obfuscate the Theta Fade video course so that it's only accessible via a private URL. Get this URL from Leo and make sure the current subscribers have it if they need it.

All good?

**Comment by highwayjourney** [comment]
@windupmicheal I will remove contents of http://tackletrade.staging.wpengine.com/theta-fade.
By the way, will you give me some URLs of Theta Fade Sensei course from live server? I might have already removed them at staging server. So I want to check if I have to restore them.

**Comment by windupmicheal** [comment]
This is still fixed, right? I added a "fixed" label. Please mark fixed items as fixed in the future for clarity. :)

**Comment by windupmicheal** [comment]
Verified that the six theta fade video pages are still available. Good good.

However, they are only available through six separate links. We should leave a single URL up that connects everything, but that URL should still be obfuscated. Leo, let's skype for this again so I can talk you through it

**Comment by windupmicheal** [comment]
Ok, checked this on the live server and it looks like all "mentions" of theta fade have been removed. The http://tackletrading.com/theta-fade-course/ link has been retained as a placeholder for theta fade content for current subscribers, but all links to this URL have been removed. The theta fade forums have been removed as well.
