### ISSUE TITLE
Search box doesn't work and boots user to front page

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#43]
Repro: type search term into search box and hit enter (options, etc)
User bounced back to front page.

**Comment by highwayjourney** [comment]
Well, I think it works well when I'm logged in. I could see it return to homepage rarely. I'm not sure why, however, guess it returns because there are links in search results that shouldn't be shared to public.
So please check when you are logged in and when you are not logged in and give me clear cases that should work correctly.

**Comment by windupmicheal** [comment]
If it's easier, you could do a screencap video and post it privately on youtube to show us what you're experiencing, @philtackletrading .

**Comment by windupmicheal** [comment]
Unless this becomes an urgent UX issue, I'm deferring this to the new website.
